/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import java.util.*;
import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AClassDefinition extends PClassDefinition
{
    private TIdentifier _first_;
    private PInheritsClass _inheritsClass_;
    private final LinkedList<PVariable> _variable_ = new LinkedList<PVariable>();
    private final LinkedList<PMethod> _method_ = new LinkedList<PMethod>();
    private TIdentifier _last_;

    public AClassDefinition()
    {
        // Constructor
    }

    public AClassDefinition(
        @SuppressWarnings("hiding") TIdentifier _first_,
        @SuppressWarnings("hiding") PInheritsClass _inheritsClass_,
        @SuppressWarnings("hiding") List<?> _variable_,
        @SuppressWarnings("hiding") List<?> _method_,
        @SuppressWarnings("hiding") TIdentifier _last_)
    {
        // Constructor
        setFirst(_first_);

        setInheritsClass(_inheritsClass_);

        setVariable(_variable_);

        setMethod(_method_);

        setLast(_last_);

    }

    @Override
    public Object clone()
    {
        return new AClassDefinition(
            cloneNode(this._first_),
            cloneNode(this._inheritsClass_),
            cloneList(this._variable_),
            cloneList(this._method_),
            cloneNode(this._last_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassDefinition(this);
    }

    public TIdentifier getFirst()
    {
        return this._first_;
    }

    public void setFirst(TIdentifier node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PInheritsClass getInheritsClass()
    {
        return this._inheritsClass_;
    }

    public void setInheritsClass(PInheritsClass node)
    {
        if(this._inheritsClass_ != null)
        {
            this._inheritsClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inheritsClass_ = node;
    }

    public LinkedList<PVariable> getVariable()
    {
        return this._variable_;
    }

    public void setVariable(List<?> list)
    {
        for(PVariable e : this._variable_)
        {
            e.parent(null);
        }
        this._variable_.clear();

        for(Object obj_e : list)
        {
            PVariable e = (PVariable) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._variable_.add(e);
        }
    }

    public LinkedList<PMethod> getMethod()
    {
        return this._method_;
    }

    public void setMethod(List<?> list)
    {
        for(PMethod e : this._method_)
        {
            e.parent(null);
        }
        this._method_.clear();

        for(Object obj_e : list)
        {
            PMethod e = (PMethod) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._method_.add(e);
        }
    }

    public TIdentifier getLast()
    {
        return this._last_;
    }

    public void setLast(TIdentifier node)
    {
        if(this._last_ != null)
        {
            this._last_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._last_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._inheritsClass_)
            + toString(this._variable_)
            + toString(this._method_)
            + toString(this._last_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._inheritsClass_ == child)
        {
            this._inheritsClass_ = null;
            return;
        }

        if(this._variable_.remove(child))
        {
            return;
        }

        if(this._method_.remove(child))
        {
            return;
        }

        if(this._last_ == child)
        {
            this._last_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((TIdentifier) newChild);
            return;
        }

        if(this._inheritsClass_ == oldChild)
        {
            setInheritsClass((PInheritsClass) newChild);
            return;
        }

        for(ListIterator<PVariable> i = this._variable_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVariable) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMethod> i = this._method_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMethod) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._last_ == oldChild)
        {
            setLast((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
