/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.node;

import com.bju.cps450.analysis.*;

@SuppressWarnings("nls")
public final class AVariable extends PVariable
{
    private TIdentifier _identifier_;
    private PType _type_;
    private PInitializer _initializer_;

    public AVariable()
    {
        // Constructor
    }

    public AVariable(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") PInitializer _initializer_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setType(_type_);

        setInitializer(_initializer_);

    }

    @Override
    public Object clone()
    {
        return new AVariable(
            cloneNode(this._identifier_),
            cloneNode(this._type_),
            cloneNode(this._initializer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariable(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PInitializer getInitializer()
    {
        return this._initializer_;
    }

    public void setInitializer(PInitializer node)
    {
        if(this._initializer_ != null)
        {
            this._initializer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initializer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._type_)
            + toString(this._initializer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._initializer_ == child)
        {
            this._initializer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._initializer_ == oldChild)
        {
            setInitializer((PInitializer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
